import { useState } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Clock3, Mail, Send, ShieldCheck } from 'lucide-react';
import { getGetDashboardSummaryQueryKey, getListOutreachQueryKey, useListOutreach, useSendOutreach } from '@workspace/api-client-react';
import type { OutreachMessage } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState, ErrorState, PageHeader, SectionLabel, SkeletonBlock } from '@/components/shell';

const dateText = (d: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(d));

export default function OutreachPage() {
  const [tab, setTab] = useState<'all' | 'queued' | 'sent'>('all');
  const params = tab === 'all' ? { limit: 100 } : { state: tab, limit: 100 };
  const messages = useListOutreach(params);
  const send = useSendOutreach(); const qc = useQueryClient();
  const sendMessage = (message: OutreachMessage) => { if (!window.confirm(`Send this demo message to ${message.toAddress}?`)) return; send.mutate({ messageId: message.id }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListOutreachQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); } }); };
  return <div><PageHeader eyebrow="Conversation desk · 02" title="Outreach" description="Review the queue, keep the language human, and send only when the signal feels earned." /><div className="mb-6 flex items-center gap-1 border-b border-border"><Tab label="All messages" value="all" active={tab} onClick={setTab} /><Tab label="Needs review" value="queued" active={tab} onClick={setTab} /><Tab label="Sent" value="sent" active={tab} onClick={setTab} /></div><div className="mb-5 grid gap-3 sm:grid-cols-3"><MiniStat label="Queued for review" value={messages.data?.filter(m => m.state === 'queued').length ?? 0} accent="gold" /><MiniStat label="Sent this week" value={messages.data?.filter(m => m.state === 'sent').length ?? 0} accent="teal" /><MiniStat label="Approval mode" value="ON" accent="navy" /></div>{messages.isLoading ? <div className="space-y-3">{[1,2,3].map(i => <SkeletonBlock key={i} className="h-44" />)}</div> : messages.isError ? <ErrorState retry={() => messages.refetch()} /> : messages.data?.length ? <div className="space-y-3">{messages.data.map((message, i) => <MessageCard key={message.id} message={message} index={i} onSend={() => sendMessage(message)} sending={send.isPending && send.variables?.messageId === message.id} />)}</div> : <EmptyState title={tab === 'queued' ? 'Queue is clear' : 'No messages here yet'} detail={tab === 'queued' ? 'A clean queue is a good queue. Draft from a lead record when you find a strong signal.' : 'Outreach will collect messages drafted from your lead workspace.'} action={<Link href="/leads" className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-xs font-bold" data-testid="link-outreach-leads"><Mail className="h-3.5 w-3.5" />Open lead workspace</Link>} />}</div>;
}

function Tab({ label, value, active, onClick }: { label: string; value: 'all' | 'queued' | 'sent'; active: string; onClick: (v: 'all' | 'queued' | 'sent') => void }) { return <button onClick={() => onClick(value)} className={`relative px-4 pb-3 pt-1 text-xs font-bold transition ${active === value ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'}`} data-testid={`button-outreach-tab-${value}`}>{label}{active === value && <span className="absolute inset-x-3 -bottom-px h-0.5 bg-[#e7b34c]" />}</button>; }
function MiniStat({ label, value, accent }: { label: string; value: string | number; accent: string }) { return <div className={`rounded-lg border border-border bg-card px-4 py-3 ${accent === 'gold' ? 'border-l-4 border-l-[#e7b34c]' : accent === 'teal' ? 'border-l-4 border-l-[#6db8a8]' : 'border-l-4 border-l-[#233553]'}`}><p className="font-mono-ui text-[9px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-1 font-display text-xl font-bold">{value}</p></div>; }
function MessageCard({ message, index, onSend, sending }: { message: OutreachMessage; index: number; onSend: () => void; sending: boolean }) { return <Card className="animate-in-up overflow-hidden" style={{ animationDelay: `${index * 60}ms` }} data-testid={`card-message-${message.id}`}><CardHeader className="flex-row items-start justify-between gap-4 border-b border-border/60 px-5 py-4 md:px-6"><div className="flex min-w-0 gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#e9e8f5] font-display text-sm font-bold text-[#58577f]">{message.leadName.slice(0, 1)}</div><div className="min-w-0"><Link href={`/leads/${message.leadId}`} className="text-sm font-bold hover:text-[#92701d]" data-testid={`link-message-lead-${message.id}`}>{message.leadName}</Link><p className="mt-0.5 flex items-center gap-1.5 text-[11px] text-muted-foreground"><Mail className="h-3 w-3" />{message.toAddress}<span className="text-border">·</span>step {message.sequenceStep}</p></div></div><span className={`flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 font-mono-ui text-[9px] font-medium uppercase ${message.state === 'sent' ? 'bg-[#e5f2ed] text-[#287660]' : 'bg-[#fff0da] text-[#a66a13]'}`}>{message.state === 'sent' ? <CheckCircle2 className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}{message.state}</span></CardHeader><CardContent className="px-5 py-4 md:px-6"><p className="text-xs font-bold">{message.subject}</p><p className="mt-3 max-w-3xl whitespace-pre-line text-xs leading-6 text-muted-foreground">{message.body}</p><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-3"><span className="font-mono-ui text-[10px] text-muted-foreground">{message.state === 'sent' && message.sentAt ? `Sent ${dateText(message.sentAt)}` : `Queued ${dateText(message.queuedAt)}`}</span>{message.state === 'queued' ? <Button onClick={onSend} disabled={sending} className="h-8 bg-[#e7b34c] px-3 text-[11px] font-bold text-[#182338] hover:bg-[#d8a936]" data-testid={`button-send-message-${message.id}`}><Send className="h-3.5 w-3.5" />{sending ? 'Sending demo...' : 'Send demo message'}</Button> : <span className="flex items-center gap-1.5 text-[11px] text-[#287660]"><ShieldCheck className="h-3.5 w-3.5" />Approved send</span>}</div></CardContent></Card>; }